### ISSUE TITLE
Remove dependencies on Windows

### ISSUE THREAD

**Issue by Crayon2000** [AlexanderBagel/FWZip#2]
Hello, would it be complicated to remove all dependencies on Windows. Your code is working great with Win32 and Win64 with a FireMonkey project on Windows. It would be great if FWZip could be multi-platform.

I know that you are using those Windows functions:
```
  function PathCanonicalizeA(lpszDes, lpszSrc: PAnsiChar): BOOL; stdcall; external 'shlwapi.dll';
  function PathCanonicalizeW(lpszDes, lpszSrc: PWideChar): BOOL; stdcall; external 'shlwapi.dll';
  function PathMakeUniqueName(pszUniqueName: PWideChar; cchMax: UINT;
    pszTemplate, pszLongPlate, pszDir: PWideChar): BOOL; stdcall; external 'shell32.dll';
```
If you need help to code your own, you can check the Wine project: https://source.winehq.org/source/dlls/shlwapi/path.c

And I *think* those types can be easily replaced:
* DWORD
* BOOL
* UINT
* TWin32FileAttributeData
* TFileTime

I am not that good in Delphi so just tell me if that's to hard to do.

Thanks!

**Comment by AlexanderBagel** [comment]
Hello Crayon,

I'll try to do it.
Stay tuned next month.

Monday, August 24, 2015, 5:48:52 AM, you wrote:




>


Hello, would it be complicated to remove all dependencies on Windows. Your code is working great with Win32 and Win64 with a FireMonkey project on Windows. It would be great if FWZip could be multi-platform.
I know that you are using those Windows functions:
  function PathCanonicalizeA(lpszDes, lpszSrc: PAnsiChar): BOOL; stdcall; external 'shlwapi.dll';
  function PathCanonicalizeW(lpszDes, lpszSrc: PWideChar): BOOL; stdcall; external 'shlwapi.dll';
  function PathMakeUniqueName(pszUniqueName: PWideChar; cchMax: UINT;
    pszTemplate, pszLongPlate, pszDir: PWideChar): BOOL; stdcall; external 'shell32.dl
If you need help to code your own, you can check the Wine project: https://source.winehq.org/source/dlls/shlwapi/path.c
And I think those types can be easily replaced:

DWORD
BOOL
UINT
TWin32FileAttributeData
TFileTime

I am not that good in Delphi so just tell me if that's to hard to do.
Thanks!
—
Reply to this email directly or view it on GitHub.








-- 
Best regards,
 Александр                            mailto:rouse79@yandex.ru

**Comment by AlexanderBagel** [comment]
Unfortunately, in the near future it is impossible.
I tried to experiment with FWZip code, but too many problems. 
Just because I do not iOS or Android developer.
May by later.
