### ISSUE TITLE
Bug in decompress

### ISSUE THREAD

**Issue by elciohadlich** [AlexanderBagel/FWZip#4]
Hello, 

I was testing FWZip to compress / unzip files and an error occurred when it was time to unzip a certain file. Attached is the file for testing compression and decompression.

I appreciate the time available.

[db_cont1.zip](https://github.com/AlexanderBagel/FWZip/files/4180817/db_cont1.zip)

**Comment by AlexanderBagel** [comment]
thanks, I`ll check

Best regards.
