### ISSUE TITLE
Exception when creating an archive 

### ISSUE THREAD

**Issue by tcount2** [AlexanderBagel/FWZip#5]
Hi!
An exception is thrown when creating any archive!
The exception is thrown in the "FWZipZLib.pas" module:

function TZCompressionStream.Seek (offset: Longint; origin: Word): Longint;
begin
   if (offset = 0) and (origin = soFromCurrent) then
   begin
     result: = FZStream.total_in;
   end
   else **raise EZCompressionError.Create (SZInvalid);**
end;

**Comment by AlexanderBagel** [comment]
Hi!
Try this sample: https://github.com/AlexanderBagel/FWZip/tree/master/Demos/Create%20ZIP%201

**Comment by tcount2** [comment]
Я только сейчас понял, что моно на русском)
Вобщем, я ваши демки пробовал разные. Но ошибка всегда одна и та же.
Исключение возникает при попытке вызвать BuildZip. При этом всегда происходит одно и то же.
Неужели только у меня так?
![Image 002](https://user-images.githubusercontent.com/94069786/141282556-8fe4fb2a-532d-44b4-a965-89140a2855d7.png)

**Comment by tcount2** [comment]
На самом деле, если проигнорировать ошибки, в итоге архив создается и он полностью рабочий.
Но почему вообще возникают данные исключения?

**Comment by AlexanderBagel** [comment]
Если честно у меня не воспроизводится. А какая версия дельфи? Там со старыми были некоторые проблемы.

**Comment by tcount2** [comment]
Хм...У меня delphi 11 alexandria.
Интересно то, что раньше и у меня все работало на версии delphi 10.2.
Но потом я установил 11, скачал по новой ваш продукт, ну и началось...
Пока непонятно, что с этим делать. Единственный костыль на данный момент - это закомментировать исключение.

**Comment by AlexanderBagel** [comment]
Ага... на 11-ой я не проверял, у меня 10.4.2 и самое интересное это то, что вызова TZCompressionStream.Seek при работе первого примера быть не должно!!! Пока подсказать не могу почему так происходит и что там поменялось в 11-ой.

**Comment by tcount2** [comment]
И еще в вашем примере исключение вызывается при создании папок вот здесь:
 // Вариант второй:
 if Zip.AddFolder('AddFolderDemo', '..\..\', '*.pas', False) = 0 then
    raise Exception.Create('Ошибка добавления данных');
--------------
возможно, это тоже связано с новой версией delphi

**Comment by tcount2** [comment]
Спасибо за ответ. Тогда буду следить за вашими обновлениями. Вряд ли я сам разберусь, что там и как работает)

**Comment by AlexanderBagel** [comment]
Вышлите пожалуйста System.Classes.pas от 11-ой версии на rouse79 (собака) yandex.ru попробую в свободное время  выцепить что там поменялось.

**Comment by tcount2** [comment]
Спасибо, модуль отправил на почту.

**Comment by AlexanderBagel** [comment]
Угу, на выходных сяду разбираться, постараюсь к понедельнику...
