### ISSUE TITLE
Пустой архив

### ISSUE THREAD

**Issue by tcount2** [AlexanderBagel/FWZip#6]
Можно ли создать совершенно пустой архив? 
Если ничего не добавлять в архив и попробовать вызвать BuildZip, то это приведет к исключению.
Грубо говоря, вот такой код не создает архив:
ZIP:=TFWZipWriter.Create;
try
ZIP.BuildZip(FileName);
except end;
FreeAndNIL(ZIP);

**Comment by AlexanderBagel** [comment]
Нет, такое не предусмотрено. А зачем?

**Comment by tcount2** [comment]
Согласен, смысла мало. 
Просто программа у меня по алгоритму сначала создает папку или архив, а только после этого наполняет файлами. 
Просто переделаю алгоритм) Спасибо за ответ.

**Comment by AlexanderBagel** [comment]
Да его проще в виде константы держать в программе ввиде массива байт и если потребуется просто выгружать на диск.

**Comment by AlexanderBagel** [comment]
Кстати - на таком простом коде исключения подниматься не должно, а можно посмотреть стек в момент возникновения исключения?

**Comment by tcount2** [comment]
Насчет исключения я перепутал. У меня просто выводилось внутреннее сообщение о том, что архив не удалось создать.
Но программного исключения все же не было)
так что, вопрос можно закрывать.

**Comment by AlexanderBagel** [comment]
Ок
