### ISSUE TITLE
Вопрос по изменению архива

### ISSUE THREAD

**Issue by tcount2** [AlexanderBagel/FWZip#7]
Здравствуйте!
Например, должен существовать некоторый архив с 10 файлами.
Задача - восстановить его, если в нем не хватает нужных файлов.
Чтобы проверить файлы хотелось бы использовать их CRC-суммы. Но в классе TFWZipModifier я не нашел такого функционала.
А сам TFWZipModifier позволяет создавать файлы с идентичными именами. 
Поэтому перезаписать уже имеющийся файл новым тоже не получится, да и зачем, если он идентичный? Но это и нужно проверять...
Открывать архив и проверять CRC не вариант, потому что архивов будет очень много.
Что можно придумать в данном случае?

**Comment by tcount2** [comment]
Я вижу решение только в объявлении публичного параметра:
property ReaderList: TReaderList read FReaderList;

**Comment by AlexanderBagel** [comment]
>>> Поэтому перезаписать уже имеющийся файл новым тоже не получится.
Перезаписать новым конечно получится. Смотри пример в папке "Demos\Modify ZIP\Replace data in ZIP"

А по поводу проверки контрольных сумм у каждого элемента в архиве есть поле Crc32, ты можешь его сравнить с контрольной суммой файла на диске.

Если что, правда я как понял это будет избыточно, но все-же...
Целостность архива (и актуальность контрольных сумм) ты можешь проверить вызовом метода TFWZipReader.Check()

Поэтому я вижу такой алгоритм действий.
1. Открываем архив, подключаем его в модификатору
2. Если не уверены в нем можно вызвать проверку целостности
3. Бежим по каждому элементу архива, находим файл соответствующий элементу на диске и считаем у него контрольную сумму
4. Если сума совпала просто добавляем элемент в модификатор вызовом AddFromZip()
5. В противном случае добавляем элемент в модификатор штатным методом AddFile()/AddStream()

**Comment by AlexanderBagel** [comment]
Или ты просто не хочешь второй раз ридером открывать и хочешь получить доступ к уже созданному ридер из модификатора?

**Comment by tcount2** [comment]
> Или ты просто не хочешь второй раз ридером открывать и хочешь получить доступ к уже созданному ридеру из модификатора?

Именно так и хочу. Ведь в случае обнаружения необходимости изменения целевого архива его по сути снова придется открывать, но уже в модификаторе.  
И получится, что сначала мы открываем архив для проверки реадером, а потом для изменения еще и модификатором.
Но, как я понял, модификатор итак открывает архив и имеет все данные в структуре FReaderList, по которой и можно пробежаться и почекать суммы CRC32. 
Разве не так?

**Comment by AlexanderBagel** [comment]
Мне не нравится эта идея, выставить наружу список приватных объектов, тогда надо будет закладываться на то что какой ни будь умник вызовет полученному обьекту метод Free.
Лучше я сделаю оверлоад метод AddZipFile который будет принимать переданный снаружи TFWZipReader, но там есть пара тройка моментов. Короче подумаю к вечер или завтра скажу что придумал.

**Comment by tcount2** [comment]
> Мне не нравится эта идея, выставить наружу список приватных объектов, тогда надо будет закладываться на то что какой ни будь умник вызовет полученному обьекту метод Free. Лучше я сделаю оверлоад метод AddZipFile который будет принимать переданный снаружи TFWZipReader, но там есть пара тройка моментов. Короче подумаю к вечер или завтра скажу что придумал.

ааааа, вы беспокоитесь за умников :) я понял)
а если функцию добавить вроде:
function GetReaderItem(const Index,ItemIndex: integer): TFWZipReaderItem;

**Comment by AlexanderBagel** [comment]
Кстати хороший вариант... да. так наверное даже лучше будет. Короче к вечеру или завтра скажу, сейчас просто занят.

**Comment by tcount2** [comment]
Хорошо, спасибо)

**Comment by tcount2** [comment]
Последнее дополнение: лучше сделать функцию-ссылку на объект ридера:
function GetReader(const Index: integer): TFWZipReader;
чтобы можно было получить и количество итемов в ридере, по которым бегать)

**Comment by AlexanderBagel** [comment]
Залил изменения. Смотри как работать в демопримере: "Demos\Modify ZIP\Replace data in ZIP"

**Comment by tcount2** [comment]
> Залил изменения. Смотри как работать в демопримере: "Demos\Modify ZIP\Replace data in ZIP"

Да, теперь есть доступ к данным архива. Спасибо за доработку)
А еще было бы бесценно, если бы можно было перезаписывать архив вместо создания нового.
Понятно, что в данном случае мешает ридер, который держит открытым поток. 
Правда, в противном случае пришлось бы хранить данные в оперативной памяти, что тоже не есть хорошо, но вполне приемлимо для небольших архивов.

**Comment by AlexanderBagel** [comment]
Это плохая концепция, хотя бы по причине того что может произойти ошибка в процессе ребилда. Поэтому правильная практика, которой придерживаются все, это создание временного файла и замена оригинала на новый вариант после полной проверки новых данных.

**Comment by tcount2** [comment]
Согласен насчет возможных ошибок и в итоге утраты архива. Дело рисковое)
