### ISSUE TITLE
Распаковка зашифрованных файлов

### ISSUE THREAD

**Issue by avp011** [AlexanderBagel/FWZip#8]
Здравствуйте,
Архив создаётся в winrar 6.21. Если задаётся пароль с установленной галкой "Традиционное(устаревшее) шифрование ZIP, то файлы распаковываются, если галку снять - нет.
Из справки winrar:
"Параметр "Традиционное (устаревшее) шифрование ZIP" доступен только при добавлении файлов в архивы ZIP. Как понятно из названия, он включает устаревший алгоритм шифрования ZIP. Если этот параметр выключен, архивы ZIP шифруются с помощью более надёжного алгоритма AES-256, но он может быть несовместим с некоторыми старыми утилитами для распаковки архивов ZIP."

**Comment by AlexanderBagel** [comment]
К сожалению пока что методы усиленной криптографии не поддерживаются и в ближайших планах таковой доработки не предвидится.

**Comment by avp011** [comment]
Хотя бы диагностику ввести на необрабатываемое шифрование, кроме Result := erNeedPassword;

**Comment by AlexanderBagel** [comment]
Ну вообще она там есть, при использовании AES должен был включаться флаг PBF_STRONG_CRYPT = 64 (шестой бит) в GeneralPurposeBitFlag, вот выдержка из документации

        Bit 6: Strong encryption.  If this bit is set, you MUST
               set the version needed to extract value to at least
               50 and you MUST also set bit 0.  If AES encryption
               is used, the version needed to extract value MUST 
               be at least 51. See the section describing the Strong
               Encryption Specification for details.  Refer to the 
               section in this document entitled "Incorporating PKWARE 
               Proprietary Technology into Your Product" for more 
               information.
               
Если этот флаг выставлен, то поднимется исключение, видимо WinRar его не выставляет

**Comment by AlexanderBagel** [comment]
Я посмотрел на WinRar как он делает, флаг он не выставляет - что является отхождением от стандарта, но он выставляет CompressionMethod: 99
Чуть попозже добавлю первичную проверку на метод сжатия, чтобы была более ранняя отсечка, еще до проверки пароля. (FWZip поддерживает только Z_NO_COMPRESSION (0) и Z_DEFLATED (8))

**Comment by avp011** [comment]
Спасибо

**Comment by AlexanderBagel** [comment]
Готово
